### ISSUE TITLE
Stretch 1 - Tracking Fish

### ISSUE THREAD

**Issue by hmparsons-sde** [hmparsons-sde/ASSIGNMENT-Bear-Watcher#9]
- [x] Dynamic click - bear has just TRIED to catch a fish.
 - [x] Dynamic click - bear has just successfully caught a fish.
 - [x] Bear Card - time stamp & status for fish attempts.
 - [x] Bear Card - time stamp & status for fish catch.
 - [x] Bear Card - running tally.
